### PR TITLE
Migrating docs from wiki

### PR DESCRIPTION
**Pull request by dusk125**
Addresses #104

### CODE REVIEW

**Comment by dusk125** [comment]
Need to fix images

**Review by bhperry — COMMENTED** [review]
Looking good! 

Other suggestions:
- Change `Home.md` to `README.md` so that it auto-renders from the docs folder
- Update root `README.md` links to docs instead of wiki

**Comment by dusk125** [comment]
While I'm working on fixing the images and adding your suggestions I do have a concern...

The docs add a bunch of images that are going to get cloned down to work on pixel... I don't *think* go will download them since they're not in a go package

**Comment by bhperry** [comment]
hmmmmm.... good point. Not terribly worried about it in terms of git clone time. Having go fetch them would be a bit strange. Should be relatively easy to validate that right?

**Comment by bhperry** [comment]
Looks like it didn't download the images

```
bhperry@DESKTOP-8M5PS14:~/workspace/pixtest$ go mod download github.com/dusk125/pixel/v2@migrate-docs
bhperry@DESKTOP-8M5PS14:~/workspace/pixtest$ ls /home/bhperry/go/pkg/mod/github.com/dusk125/pixel/v2@v2.0.0-20240818024155-23bff67f13dd/docs/
Basics  Compilation  README.md
```

**Comment by dusk125** [comment]
Awesome! Thanks for validating that

**Review by bhperry — APPROVED** [review]
LGTM

**Pull request merged**
